trigger: none
pr: none

# Bu iş akışı, v2-ci-ftp-matrix pipeline'ı tamamlandığında çalışır
resources:
  pipelines:
    - pipeline: ci
      source: v2-ci-ftp-matrix
      trigger:
        branches:
          include:
            - main

# Runner, işin çalışacağı konak makine
pool:
  vmImage: ubuntu-latest

# İşler
jobs:
# İş: CD adımlarını yürütür, publish çıktısını deploy eder
- job: cd
  displayName: CD Matrix (FTP/FTPS)
  # Strateji ayarı
  strategy:
    # Matrix ile paralel çalıştırma
    matrix:
      # 1. uygulamanın bilgileri
      V2Site:
        name: V2.Site
        target: site
        artifactName: v2-site-publish
        ftpServer: $(V2_SITE_FTP_SERVER)
        ftpUsername: $(V2_SITE_FTP_USERNAME)
        ftpPassword: $(V2_SITE_FTP_PASSWORD)
        ftpRemoteDir: $(V2_SITE_FTP_REMOTE_DIR)

      # 2. uygulamanın bilgileri
      V2Admin:
        name: V2.Admin
        target: admin
        artifactName: v2-admin-publish
        ftpServer: $(V2_ADMIN_FTP_SERVER)
        ftpUsername: $(V2_ADMIN_FTP_USERNAME)
        ftpPassword: $(V2_ADMIN_FTP_PASSWORD)
        ftpRemoteDir: $(V2_ADMIN_FTP_REMOTE_DIR)

  # İşin adımları
  steps:
  # Adım: Artifact indirir
  - download: ci
    artifact: $(artifactName)
    continueOnError: true

  # Adım: Artifact klasörünün varlığını kontrol eder
  - bash: |
      if [ -d "$(Pipeline.Workspace)/ci/$(artifactName)" ]; then
        echo "##vso[task.setvariable variable=artifactExists]true"
      else
        echo "##vso[task.setvariable variable=artifactExists]false"
      fi
    displayName: Check Artifact

  # Adım: FTP ile deploy eder
  - bash: |
      sudo apt-get update
      sudo apt-get install -y lftp
      lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_SERVER" -e "set ftp:ssl-force true; set ftp:ssl-protect-data true; mirror -R --verbose $(Pipeline.Workspace)/ci/v2-site-publish $FTP_REMOTE_DIR; bye"
    displayName: Deploy via FTP
    # Bu adım, indirme adımı başarılıysa çalışır
    condition: eq(variables['artifactExists'], 'true')
    env:
      FTP_SERVER: $(ftpServer)
      FTP_USERNAME: $(ftpUsername)
      FTP_PASSWORD: $(ftpPassword)
      FTP_REMOTE_DIR: $(ftpRemoteDir)

  # Adım: Artifact olmadığı için bilgilendirme mesajı yazar
  - bash: echo "$(name) icin artifact olmadigi icin deploy atlandi."
    displayName: Skip Deploy Info
    # Bu adım, indirme adımı başarısızsa çalışır
    condition: ne(variables['artifactExists'], 'true')
