
name: v2-ci-cd-azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


env:
  DOTNET_VERSION: "10.0.x"
  SITE_PROJECT_PATH: "V2.Site/V2.Site.csproj"
  SITE_TEST_PATH: "V2.Site.Tests/V2.Site.Tests.csproj"
  ADMIN_PROJECT_PATH: "V2.Admin/V2.Admin.csproj"
  ADMIN_TEST_PATH: "V2.Admin.Tests/V2.Admin.Tests.csproj"
  SITE_PUBLISH_DIR: "v2-site-publish"
  ADMIN_PUBLISH_DIR: "v2-admin-publish"

jobs:
  detect_changes:
    name: Detect Changed Projects
    runs-on: ubuntu-latest
    outputs:
      shared_changed: ${{ steps.filter.outputs.shared }}
      site_changed: ${{ steps.filter.outputs.site }}
      admin_changed: ${{ steps.filter.outputs.admin }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Path Filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            shared:
              - 'V2.Shared/**'
            site:
              - 'V2.Site/**'
              - 'V2.Site.Tests/**'
              - 'V2.sln'
            admin:
              - 'V2.Admin/**'
              - 'V2.Admin.Tests/**'
              - 'V2.sln'

      - name: Print Change Summary
        run: |
          echo "shared_changed: ${{ steps.filter.outputs.shared }}"
          echo "site_changed: ${{ steps.filter.outputs.site }}"
          echo "admin_changed: ${{ steps.filter.outputs.admin }}"

  site_ci:
    name: CI Site (Build, Test, Publish)
    runs-on: ubuntu-latest
    needs: detect_changes
    if: github.event_name == 'workflow_dispatch' || needs.detect_changes.outputs.shared_changed == 'true' || needs.detect_changes.outputs.site_changed == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Site
        run: dotnet restore ${{ env.SITE_PROJECT_PATH }}

      - name: Restore Site Tests
        run: dotnet restore ${{ env.SITE_TEST_PATH }}

      - name: Build Site
        run: dotnet build ${{ env.SITE_PROJECT_PATH }} --configuration Release --no-restore

      - name: Test Site
        run: dotnet test ${{ env.SITE_TEST_PATH }} --configuration Release --verbosity normal --no-restore

      - name: Publish Site
        run: dotnet publish ${{ env.SITE_PROJECT_PATH }} --configuration Release --output ${{ env.SITE_PUBLISH_DIR }} --no-build

      - name: Upload Site Artifact
        uses: actions/upload-artifact@v4
        with:
          name: v2-site-publish
          path: ${{ env.SITE_PUBLISH_DIR }}
          if-no-files-found: error

  admin_ci:
    name: CI Admin (Build, Test, Publish)
    runs-on: ubuntu-latest
    needs: detect_changes
    if: github.event_name == 'workflow_dispatch' || needs.detect_changes.outputs.shared_changed == 'true' || needs.detect_changes.outputs.admin_changed == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Admin
        run: dotnet restore ${{ env.ADMIN_PROJECT_PATH }}

      - name: Restore Admin Tests
        run: dotnet restore ${{ env.ADMIN_TEST_PATH }}

      - name: Build Admin
        run: dotnet build ${{ env.ADMIN_PROJECT_PATH }} --configuration Release --no-restore

      - name: Test Admin
        run: dotnet test ${{ env.ADMIN_TEST_PATH }} --configuration Release --verbosity normal --no-restore

      - name: Publish Admin
        run: dotnet publish ${{ env.ADMIN_PROJECT_PATH }} --configuration Release --output ${{ env.ADMIN_PUBLISH_DIR }} --no-build

      - name: Upload Admin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: v2-admin-publish
          path: ${{ env.ADMIN_PUBLISH_DIR }}
          if-no-files-found: error

  site_cd:
    name: CD Site (Azure App Service)
    runs-on: ubuntu-latest
    needs:
      - detect_changes
      - site_ci
    if: (github.event_name == 'workflow_dispatch' || needs.detect_changes.outputs.shared_changed == 'true' || needs.detect_changes.outputs.site_changed == 'true')

    steps:
      - name: Download Site Artifact
        uses: actions/download-artifact@v4
        with:
          name: v2-site-publish
          path: ./site-artifact

      - name: Deploy Site to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.V2_SITE_AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.V2_SITE_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./site-artifact

  admin_cd:
    name: CD Admin (Azure App Service)
    runs-on: ubuntu-latest
    needs:
      - detect_changes
      - admin_ci
    if: (github.event_name == 'workflow_dispatch' || needs.detect_changes.outputs.shared_changed == 'true' || needs.detect_changes.outputs.admin_changed == 'true') && github.event_name != 'pull_request' && github.ref == 'refs/heads/main'

    steps:
      - name: Download Admin Artifact
        uses: actions/download-artifact@v4
        with:
          name: v2-admin-publish
          path: ./admin-artifact

      - name: Deploy Admin to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.V2_ADMIN_AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.V2_ADMIN_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./admin-artifact
