
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: ci
      source: v1-ci-ftp
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: ubuntu-latest

jobs:
- job: deploy
  displayName: CD (Download Artifact + FTP Deploy)
  steps:
  - download: ci
    artifact: v1-webapp-publish
    
  - bash: |
      sudo apt-get update
      sudo apt-get install -y lftp
      lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_SERVER" -e "set ftp:ssl-force true; set ftp:ssl-protect-data true; mirror -R --verbose $(Pipeline.Workspace)/ci/v1-s04-webapp-publish $FTP_REMOTE_DIR; bye"
    displayName: Deploy via FTP
    env:
      FTP_SERVER: $(V1_FTP_SERVER)
      FTP_USERNAME: $(V1_FTP_USERNAME)
      FTP_PASSWORD: $(V1_FTP_PASSWORD)
      FTP_REMOTE_DIR: $(V1_FTP_REMOTE_DIR)
