
trigger: none
pr: none

parameters:
- name: sourceDir
  displayName: Source remote directory
  type: string
  default: /site/wwwroot/
- name: targetDir
  displayName: Target remote directory
  type: string
  default: /site/wwwroot/
- name: deleteExtra
  displayName: Delete files on target that do not exist on source
  type: boolean
  default: false

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    set -e
    test -n "$SRC_SERVER"
    test -n "$SRC_USERNAME"
    test -n "$SRC_PASSWORD"
    test -n "$DST_SERVER"
    test -n "$DST_USERNAME"
    test -n "$DST_PASSWORD"
  displayName: Validate configuration
  env:
    SRC_SERVER: $(V1_SOURCE_FTP_SERVER)
    SRC_USERNAME: $(V1_SOURCE_FTP_USERNAME)
    SRC_PASSWORD: $(V1_SOURCE_FTP_PASSWORD)
    DST_SERVER: $(V1_TARGET_FTP_SERVER)
    DST_USERNAME: $(V1_TARGET_FTP_USERNAME)
    DST_PASSWORD: $(V1_TARGET_FTP_PASSWORD)

- bash: |
    sudo apt-get update
    sudo apt-get install -y lftp
  displayName: Install lftp

- bash: |
    set -e
    LOCAL_DIR="$(Agent.TempDirectory)/ftp-clone"
    rm -rf "$LOCAL_DIR"
    mkdir -p "$LOCAL_DIR"

    lftp -u "$SRC_USERNAME","$SRC_PASSWORD" "$SRC_SERVER" -e "set ssl:verify-certificate no; set ftp:passive-mode true; mirror --verbose '$SOURCE_DIR' '$LOCAL_DIR'; bye"

    DELETE_FLAG=""
    if [ "$DELETE_EXTRA" = "true" ]; then
      DELETE_FLAG="--delete"
    fi

    lftp -u "$DST_USERNAME","$DST_PASSWORD" "$DST_SERVER" -e "set ssl:verify-certificate no; set ftp:passive-mode true; mirror -R --verbose $DELETE_FLAG '$LOCAL_DIR' '$TARGET_DIR'; bye"
  displayName: FTP mirror source to target
  env:
    SRC_SERVER: $(V1_SOURCE_FTP_SERVER)
    SRC_USERNAME: $(V1_SOURCE_FTP_USERNAME)
    SRC_PASSWORD: $(V1_SOURCE_FTP_PASSWORD)
    DST_SERVER: $(V1_TARGET_FTP_SERVER)
    DST_USERNAME: $(V1_TARGET_FTP_USERNAME)
    DST_PASSWORD: $(V1_TARGET_FTP_PASSWORD)
    SOURCE_DIR: ${{ parameters.sourceDir }}
    TARGET_DIR: ${{ parameters.targetDir }}
    DELETE_EXTRA: ${{ parameters.deleteExtra }}
