name: v1-ci-cd-azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: "10.0.x"
  SOLUTION_PATH: "V1.sln"
  PROJECT_PATH: "V1.Web/V1.Web.csproj"
  PUBLISH_DIR: "v1-publish"

jobs:
  ci:
    name: CI (Build, Test, Publish)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-build --verbosity normal

      - name: Publish Web App
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --output ${{ env.PUBLISH_DIR }} --no-build

      - name: Upload Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: v1-webapp-publish
          path: ${{ env.PUBLISH_DIR }}
          if-no-files-found: error

  cd:
    name: CD (Deploy to Azure App Service)
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Download Publish Artifact
        uses: actions/download-artifact@v4
        with:
          name: v1-webapp-publish
          path: ./artifact

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.V1_AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.V1_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./artifact

