
name: v1-ftp-clone


on:
  workflow_dispatch:
    inputs:
      source_dir:
        required: true
        default: /site/wwwroot/
      target_dir:
        required: true
        default: /site/wwwroot/
      delete_extra:
        type: boolean
        required: true
        default: false

jobs:
  ftp_clone:
    name: FTP Clone V1
    runs-on: ubuntu-latest
    env:
      SRC_SERVER: ${{ secrets.V1_SOURCE_FTP_SERVER }}
      SRC_USERNAME: ${{ secrets.V1_SOURCE_FTP_USERNAME }}
      SRC_PASSWORD: ${{ secrets.V1_SOURCE_FTP_PASSWORD }}
      DST_SERVER: ${{ secrets.V1_TARGET_FTP_SERVER }}
      DST_USERNAME: ${{ secrets.V1_TARGET_FTP_USERNAME }}
      DST_PASSWORD: ${{ secrets.V1_TARGET_FTP_PASSWORD }}

    steps:
      - name: Validate configuration
        run: |
          test -n "$SRC_SERVER"
          test -n "$SRC_USERNAME"
          test -n "$SRC_PASSWORD"
          test -n "$DST_SERVER"
          test -n "$DST_USERNAME"
          test -n "$DST_PASSWORD"

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Mirror source FTP to runner
        run: |
          set -e
          LOCAL_DIR="$RUNNER_TEMP/ftp-clone"
          rm -rf "$LOCAL_DIR"
          mkdir -p "$LOCAL_DIR"

          lftp -u "$SRC_USERNAME","$SRC_PASSWORD" "$SRC_SERVER" -e "set ssl:verify-certificate no; set ftp:passive-mode true; mirror --verbose '${{ inputs.source_dir }}' '$LOCAL_DIR'; bye"

      - name: Mirror runner to target FTP
        run: |
          set -e
          LOCAL_DIR="$RUNNER_TEMP/ftp-clone"
          DELETE_FLAG=""
          if [ "${{ inputs.delete_extra }}" = "true" ]; then
            DELETE_FLAG="--delete"
          fi

          lftp -u "$DST_USERNAME","$DST_PASSWORD" "$DST_SERVER" -e "set ssl:verify-certificate no; set ftp:passive-mode true; mirror -R --verbose $DELETE_FLAG '$LOCAL_DIR' '${{ inputs.target_dir }}'; bye"
